### ISSUE TITLE
argument parsing failure....

### ISSUE THREAD

**Issue by bll123** [xdobry/tclsqueak#14]
Platform: Linux Mint 17.2
Segfaults with tcl 8.6.1 and xotcl 1.6.7 (standard linux mint packages).  An xotcl issue -- fails on the package require.

With tcl 8.5.15 and xotcl 1.6.7, none of the arguments get parsed properly.   If I specify more than one .tcl file on the command line it fails.  If I specify a .tcl file in a sub-directory (e.g. code/bdjmsgs.tcl) it fails.

warn: parsing -scan .
can't read "lineCount": no such variable
    while executing
"incr allLinesCount $lineCount"
    (procedure "parseFilesPass" line 8)
    ::xotcl::__#0 ::PrsFileContext->parseFilesPass
    invoked from within
[...]

**Comment by xdobry** [comment]
segfaults are problems of tcl core and binary extension. I suppose your xotcl 1.6.7 binary does not fit to your tcl 8.6.1.
In such situation the best is to build xotcl yourself.
I use for developing tcl 8.6 and XOTcl2 from https://next-scripting.org
I will adapt the ReadMe

Also package require issue is the problem of right installation of XOTcl.

There is really a bug in start script of the program.
For quick fix change the lines in IDETclParser.xotcl

From
PrsFileContext proc startFromShell args {
    set fileContext [PrsFileContext new]
    $fileContext startWithArgs $args
}

To
PrsFileContext proc startFromShell argv {
    set fileContext [PrsFileContext new]
    $fileContext startWithArgs $argv
}
