### ISSUE TITLE
win7: problem executing ttclcheck.exe

### ISSUE THREAD

**Issue by bll123** [xdobry/tclsqueak#27]
Trying out the .exe from the ttclcheck web page on Windows 7:

C:\Users\bll\Desktop\BallroomDJ>"C:\Users\bll\Downloads\ttclcheck.exe" -scan . -w chk.sig
wrong # args: should be "startFromShell argv"
    ::PrsFileContext->startFromShell
    invoked from within
"PrsFileContext startFromShell {*}$argv"
    invoked from within
"if {[starkit::startup] ne "sourced"} {

package require XOTcl
namespace import ::xotcl::*

source [file join $::starkit::topdir IDETclParser.xotcl]
so..."
    (file "C:/Users/bll/Downloads/ttclcheck.exe/main.tcl" line 3)

C:\Users\bll\Desktop\BallroomDJ>

**Comment by xdobry** [comment]
It was problem with start up of tclkit of ttclcheck.exe
I have fixed updated it on the site 
http://www.xdobry.de/ttclcheck/ without changing the version
